name: fvm_app
description: Flutter Version Manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-alpha.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  
  dio_http_cache: ^0.2.11
  dio: ^3.0.10
  flutter_cache_manager: ^2.0.0
  flutter:
    sdk: flutter
    
  oktoast: ^2.3.2
  settings_ui: ^0.4.0
  material_floating_search_bar: 0.2.2
  flutter_spinkit: ^4.1.2+1
  flutter_markdown: ^0.5.0
  material_design_icons_flutter: ^4.0.5755
  animations: ^1.1.2
  
  async: ^2.4.2
  pubspec_yaml: ^2.0.1
  url_launcher: ^5.7.6
  watcher: ^0.9.7+15
  google_fonts: ^1.1.1
  filesize: ^1.0.4
  date_time_format: ^1.1.0
  hooks_riverpod: ^0.12.1
  freezed: ^0.12.2
  flutter_hooks: ^0.14.1
  path_provider: ^1.6.21

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  fvm:
    path: ../cli
  pub_api_client: 1.0.8

dev_dependencies:
  build_runner: ^1.10.3
  effective_dart: ^1.2.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/getting_started.md

