name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support channels, releases, and local cache for fast switching between versions.
version: 1.3.5
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  fvm: main

dependencies:
  
  meta: ^1.2.3
  pretty_json: ^1.0.9
  pubspec_yaml: ^2.0.1

  args: ^1.6.0
  cli_util: ^0.2.0
  console: ^3.1.0
  io: ^0.3.4
  path: ^1.6.4
  process_run: ^0.11.0+2
  http: ^0.12.2
  date_format: ^1.0.9
  version: ^1.2.0
  cli_dialog: ^0.3.3
  pub_api_client: ^1.0.9


dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.3
  build_runner: ^1.10.0
  build_version: ^2.0.1
  build_test: ^1.2.2
  grinder: ^0.8.6
  dotenv: ^2.0.0
  # cli_pkg: ^1.0.0-beta.9
  cli_pkg:
    git:
      url: https://github.com/leoafarias/dart_cli_pkg.git
      ref: chocolatey-deploy-fix

