name: Chocolatey Deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy-windows:
    name: Cholatey Deploy (Windows)
    runs-on: windows-latest
    env:
      CHOCOLATEY_TOKEN: ${{ secrets.CHOCOLATEY_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run Builder for Version
        run: dart pub run build_runner build --delete-conflicting-outputs

      - name: Run Test
        run: dart pub run test

      - name: Deploy Chocolatey (Windows)
        run: dart pub run grinder pkg-chocolatey-deploy
